// ISO 3166-1 alpha-3 passport countries (top ~80 by global traveller volume)
export const PASSPORT_COUNTRIES: { code: string; name: string }[] = [
  { code: 'AFG', name: 'Afghanistan' },
  { code: 'ALB', name: 'Albania' },
  { code: 'DZA', name: 'Algeria' },
  { code: 'ARG', name: 'Argentina' },
  { code: 'ARM', name: 'Armenia' },
  { code: 'AUS', name: 'Australia' },
  { code: 'AUT', name: 'Austria' },
  { code: 'AZE', name: 'Azerbaijan' },
  { code: 'BHR', name: 'Bahrain' },
  { code: 'BGD', name: 'Bangladesh' },
  { code: 'BEL', name: 'Belgium' },
  { code: 'BLR', name: 'Belarus' },
  { code: 'BRA', name: 'Brazil' },
  { code: 'CAN', name: 'Canada' },
  { code: 'CHL', name: 'Chile' },
  { code: 'CHN', name: 'China' },
  { code: 'COL', name: 'Colombia' },
  { code: 'HRV', name: 'Croatia' },
  { code: 'CZE', name: 'Czech Republic' },
  { code: 'DNK', name: 'Denmark' },
  { code: 'EGY', name: 'Egypt' },
  { code: 'ETH', name: 'Ethiopia' },
  { code: 'FIN', name: 'Finland' },
  { code: 'FRA', name: 'France' },
  { code: 'GEO', name: 'Georgia' },
  { code: 'DEU', name: 'Germany' },
  { code: 'GHA', name: 'Ghana' },
  { code: 'GRC', name: 'Greece' },
  { code: 'HUN', name: 'Hungary' },
  { code: 'IND', name: 'India' },
  { code: 'IDN', name: 'Indonesia' },
  { code: 'IRN', name: 'Iran' },
  { code: 'IRQ', name: 'Iraq' },
  { code: 'IRL', name: 'Ireland' },
  { code: 'ISR', name: 'Israel' },
  { code: 'ITA', name: 'Italy' },
  { code: 'JPN', name: 'Japan' },
  { code: 'JOR', name: 'Jordan' },
  { code: 'KAZ', name: 'Kazakhstan' },
  { code: 'KEN', name: 'Kenya' },
  { code: 'KWT', name: 'Kuwait' },
  { code: 'LBN', name: 'Lebanon' },
  { code: 'LBY', name: 'Libya' },
  { code: 'MYS', name: 'Malaysia' },
  { code: 'MEX', name: 'Mexico' },
  { code: 'MAR', name: 'Morocco' },
  { code: 'NLD', name: 'Netherlands' },
  { code: 'NZL', name: 'New Zealand' },
  { code: 'NGA', name: 'Nigeria' },
  { code: 'NOR', name: 'Norway' },
  { code: 'PAK', name: 'Pakistan' },
  { code: 'PHL', name: 'Philippines' },
  { code: 'POL', name: 'Poland' },
  { code: 'PRT', name: 'Portugal' },
  { code: 'QAT', name: 'Qatar' },
  { code: 'ROU', name: 'Romania' },
  { code: 'RUS', name: 'Russia' },
  { code: 'SAU', name: 'Saudi Arabia' },
  { code: 'SEN', name: 'Senegal' },
  { code: 'ZAF', name: 'South Africa' },
  { code: 'KOR', name: 'South Korea' },
  { code: 'ESP', name: 'Spain' },
  { code: 'SWE', name: 'Sweden' },
  { code: 'CHE', name: 'Switzerland' },
  { code: 'SYR', name: 'Syria' },
  { code: 'TWN', name: 'Taiwan' },
  { code: 'TUN', name: 'Tunisia' },
  { code: 'TUR', name: 'Turkey' },
  { code: 'UKR', name: 'Ukraine' },
  { code: 'ARE', name: 'United Arab Emirates' },
  { code: 'GBR', name: 'United Kingdom' },
  { code: 'USA', name: 'United States' },
  { code: 'UZB', name: 'Uzbekistan' },
  { code: 'VNM', name: 'Vietnam' },
  { code: 'YEM', name: 'Yemen' },
];

// ISO 3166-1 alpha-2 destination countries for the visa input
export const DESTINATION_COUNTRIES: { code: string; name: string }[] = [
  { code: 'AT', name: 'Austria (Schengen)' },
  { code: 'BE', name: 'Belgium (Schengen)' },
  { code: 'BR', name: 'Brazil' },
  { code: 'CA', name: 'Canada' },
  { code: 'CN', name: 'China' },
  { code: 'DE', name: 'Germany (Schengen)' },
  { code: 'EG', name: 'Egypt' },
  { code: 'ES', name: 'Spain (Schengen)' },
  { code: 'FR', name: 'France (Schengen)' },
  { code: 'GB', name: 'United Kingdom' },
  { code: 'GR', name: 'Greece (Schengen)' },
  { code: 'IN', name: 'India' },
  { code: 'ID', name: 'Indonesia' },
  { code: 'IT', name: 'Italy (Schengen)' },
  { code: 'JP', name: 'Japan' },
  { code: 'MA', name: 'Morocco' },
  { code: 'MX', name: 'Mexico' },
  { code: 'NL', name: 'Netherlands (Schengen)' },
  { code: 'NZ', name: 'New Zealand' },
  { code: 'NG', name: 'Nigeria' },
  { code: 'PL', name: 'Poland (Schengen)' },
  { code: 'PT', name: 'Portugal (Schengen)' },
  { code: 'QA', name: 'Qatar' },
  { code: 'SA', name: 'Saudi Arabia' },
  { code: 'SG', name: 'Singapore' },
  { code: 'ZA', name: 'South Africa' },
  { code: 'KR', name: 'South Korea' },
  { code: 'SE', name: 'Sweden (Schengen)' },
  { code: 'CH', name: 'Switzerland (Schengen)' },
  { code: 'TH', name: 'Thailand' },
  { code: 'TR', name: 'Turkey' },
  { code: 'AE', name: 'United Arab Emirates' },
  { code: 'US', name: 'United States' },
  { code: 'VN', name: 'Vietnam' },
];

export const VISA_TYPES = [
  { value: 'schengen', label: 'Schengen (Type C)' },
  { value: 'tourist', label: 'Tourist' },
  { value: 'business', label: 'Business' },
  { value: 'work', label: 'Work' },
  { value: 'student', label: 'Student' },
  { value: 'transit', label: 'Transit' },
];

export const REGIONS = [
  { value: '', label: 'All Regions' },
  { value: 'Europe', label: 'Europe' },
  { value: 'Asia', label: 'Asia' },
  { value: 'Africa', label: 'Africa' },
  { value: 'Americas', label: 'Americas' },
  { value: 'Middle East', label: 'Middle East' },
  { value: 'Oceania', label: 'Oceania' },
];

export const SORT_OPTIONS = [
  { value: 'price', label: 'Cheapest first' },
  { value: 'safety', label: 'Safest first' },
  { value: 'temperature', label: 'Warmest first' },
];
